# Generated by Django 5.2.6 on 2026-05-16 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='absent_days',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='continuous_attendance_days',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='da',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='hra',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='leave_days',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='present_days',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='working_days',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AdminControlledData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('da', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_data', to='employees.employeeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.IntegerField(default=30)),
                ('present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('leave_days', models.IntegerField(default=0)),
                ('continuous_attendance_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('warning', 'Warning'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_record', to='employees.admincontrolleddata')),
            ],
        ),
    ]
