# Generated by Django 5.2.6 on 2026-05-17 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employeeprofile_absent_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='employee_id',
        ),
    ]
