# Generated by Django 5.2.14 on 2026-05-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_leaverecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='emp_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
