# Generated by Django 5.2.6 on 2026-05-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeeprofile_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('hr', 'Human Resources'), ('finance', 'Finance'), ('it', 'Information Technology'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('admin', 'Administration')], max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='admin_data',
        ),
        migrations.RemoveField(
            model_name='admincontrolleddata',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='admincontrolleddata',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='admincontrolleddata',
            name='da',
        ),
        migrations.RemoveField(
            model_name='admincontrolleddata',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='admincontrolleddata',
            name='hra',
        ),
        migrations.AddField(
            model_name='admincontrolleddata',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('admin', 'Admin'), ('hr', 'HR')], default='employee', max_length=50),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='EmployeeAttendance',
        ),
    ]
