# Generated by Django 5.2.14 on 2026-05-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employeeprofile_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRecord',
        ),
    ]
