# Generated by Django 5.2.14 on 2026-06-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_delete_leaverecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='avatar_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
