# Generated by Django 5.2.14 on 2026-07-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employeeprofile_avatar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('hr', 'Human Resources'), ('finance', 'Finance'), ('it', 'Information Technology'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('admin', 'Administration'), ('accountant', 'Accountant'), ('positive_vibes', 'Positive Vibes Department')], max_length=50, null=True),
        ),
    ]
