# Generated by Django 5.2.14 on 2026-05-15 09:13
# Edited: the original AlterField (BigAutoField -> UUIDField) generates
# `ALTER COLUMN "id" TYPE uuid USING "id"::uuid` on Postgres, but Postgres
# has no cast from bigint to uuid, so this always fails on a fresh Postgres
# database (works "by accident" on SQLite, which doesn't enforce this).
# Since this table is always empty at this exact point in migration history
# (it was just created one migration ago), we don't need to preserve any
# existing id values - a fresh gen_random_uuid() per (nonexistent) row is
# fine. SQLite still goes through Django's normal schema-editor field
# alteration (already-applied databases are unaffected either way, since
# Django tracks applied migrations by name, not by operation content).

import uuid
from django.db import migrations, models


def alter_user_id_to_uuid(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        # Several tables have a live FK to User.id at this exact point in
        # migration history: the dead-code OTP model (dropped 5 migrations
        # later in 0007), and - easy to miss - Django's own auto-created M2M
        # "through" tables for User.groups and User.user_permissions
        # (accounts_user_groups, accounts_user_user_permissions), which
        # exist for the lifetime of the app. A FK blocks changing the type
        # of the column it references, so for every such table: drop the FK
        # constraint, then ALSO convert that table's own referencing column
        # to uuid (safe - all of these tables are guaranteed empty here,
        # since this runs immediately after User is first created and before
        # any group/permission/OTP could possibly have been assigned yet).
        schema_editor.execute("""
            DO $$
            DECLARE
                r RECORD;
                col_name text;
            BEGIN
                FOR r IN
                    SELECT conname, conrelid::regclass AS table_name, conrelid, conkey
                    FROM pg_constraint
                    WHERE confrelid = 'accounts_user'::regclass
                      AND contype = 'f'
                LOOP
                    SELECT attname INTO col_name
                    FROM pg_attribute
                    WHERE attrelid = r.conrelid AND attnum = r.conkey[1];

                    EXECUTE format('ALTER TABLE %%s DROP CONSTRAINT %%I', r.table_name, r.conname);
                    EXECUTE format('ALTER TABLE %%s ALTER COLUMN %%I TYPE uuid USING gen_random_uuid()', r.table_name, col_name);
                END LOOP;
            END $$;
        """)
        # Django 4.1+ creates BigAutoField PKs on Postgres as identity columns
        # (GENERATED BY DEFAULT AS IDENTITY) rather than the older
        # sequence+DEFAULT approach, so DROP DEFAULT doesn't apply here.
        schema_editor.execute('ALTER TABLE accounts_user ALTER COLUMN id DROP IDENTITY IF EXISTS')
        schema_editor.execute(
            'ALTER TABLE accounts_user ALTER COLUMN id TYPE uuid USING gen_random_uuid()'
        )
    else:
        User = apps.get_model('accounts', 'User')
        old_field = models.BigAutoField(auto_created=True, primary_key=True, serialize=False)
        old_field.set_attributes_from_name('id')
        old_field.model = User
        new_field = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)
        new_field.set_attributes_from_name('id')
        new_field.model = User
        schema_editor.alter_field(User, old_field, new_field)


def alter_user_id_to_bigint(apps, schema_editor):
    raise NotImplementedError("Reversing this migration is not supported.")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='user',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
            database_operations=[
                migrations.RunPython(alter_user_id_to_uuid, alter_user_id_to_bigint),
            ],
        ),
    ]
