# Generated by Django 5.2.14 on 2026-05-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_otp_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='purpose',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
