# Generated by Django 5.2.14 on 2026-05-15 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_otp_otp_code_remove_otp_is_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='code',
            new_name='otp',
        ),
        migrations.AddField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('verify', 'Verification')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
