# Generated by Django 5.2.14 on 2026-05-15 09:55
# Edited: the original AddField used `default=django.utils.timezone.now` (a
# datetime) as the one-time backfill value for a CharField(max_length=20) -
# on Postgres this tries to insert the full timestamp string (~32 chars)
# into a varchar(20) column, failing with "value too long for type
# character varying(20)" on any fresh database (SQLite doesn't enforce
# varchar length limits, so this only ever surfaced on Postgres). Since
# preserve_default=False means this value is only used for backfilling the
# (always-empty, dead-code) accounts_otp table, any valid short value works.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_otp_otp_code_remove_otp_is_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='code',
            new_name='otp',
        ),
        migrations.AddField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('verify', 'Verification')], default='login', max_length=20),
            preserve_default=False,
        ),
    ]
