# Generated by Django 5.2.14 on 2026-05-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_code_otp_otp_otp_is_used_otp_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
    ]
