"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.contrib.messages import constants as messages
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to the old hardcoded dev key only when SECRET_KEY isn't set in
# the environment, so local dev keeps working without a .env file.
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-tnpg7zk*c5!9*p0-2jemqyj+o9!jgh-l%zd^s2h%an!knu4vci',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='*,192.168.1.7,127.0.0.1,localhost',
    cast=Csv(),
)

# When accessing the dev server by IP from other devices, include
# those origins so Django's CSRF check accepts POSTs from them.
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://127.0.0.1,http://127.0.0.1:8000,http://192.168.1.7,http://192.168.1.7:8000',
    cast=Csv(),
)

# Secure by default in production (DEBUG=False); relaxed locally over HTTP.
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'  # Allow form submissions from same site

# Disable the Cross-Origin-Opener-Policy header when using HTTP/local IP.
# This avoids browser warnings for non-HTTPS local network access.
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

# Database connection pooling (stops DB from being a bottleneck)
CONN_MAX_AGE = 60  # reuse DB connections for 60 seconds


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # NOTE: 'cloudinary_storage'/'cloudinary' are intentionally NOT registered
    # here. Their storage classes (used below in STORAGES) work fine as plain
    # importable classes without app registration, and registering
    # 'cloudinary_storage' makes Django use ITS collectstatic override, which
    # silently skips copying most static files unless STATICFILES_STORAGE is
    # its own Cloudinary-static backend (which we don't use - only Cloudinary
    # for media, not static). That bug broke `collectstatic` on Vercel/Render.

    # CUSTOM APPS
    'accounts',
    'employees',
    'attendance',
    'leaves',
    'payroll',
    'dashboard',
    'reports',
    'noticeboard',
    'grievances',
    'mantech_chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',        # ← ADD THIS LINE
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # ← for debugging 
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'grievances.context_processors.admin_notifications',
                'django.template.context_processors.media',  # ← add this for media files
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 20,
            'init_command': (
                'PRAGMA journal_mode=WAL;'      # ← biggest fix — allows multiple readers + 1 writer at same time
                'PRAGMA synchronous=NORMAL;'    # ← faster writes
                'PRAGMA cache_size=-64000;'     # ← 64MB memory cache
                'PRAGMA temp_store=MEMORY;'     # ← temp tables in RAM
                # 'PRAGMA mmap_size=268435456;'   # ← 256MB memory map
            ),
        }
    }
}

# On Vercel (or any host that sets DATABASE_URL), use Postgres instead of the
# local SQLite file above — SQLite's on-disk file doesn't survive a
# serverless/ephemeral filesystem. Local dev is untouched when this env var
# isn't set.
_DATABASE_URL = config('DATABASE_URL', default='')
if _DATABASE_URL:
    import dj_database_url
    DATABASES['default'] = dj_database_url.config(default=_DATABASE_URL, conn_max_age=60)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CUSTOM CONFIGURATION SETTINGS

## settings.py
# SESSION_COOKIE_AGE = 86400          # 1 day in seconds (default is 2 weeks)
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # keep session after browser closes
# SESSION_SAVE_EVERY_REQUEST = True   # refresh session on every request

# settings.py
LOGIN_URL = "/accounts/login/"           # must match your actual login url
LOGIN_REDIRECT_URL = "/"



# FOR DATE
TIME_ZONE = 'Asia/Kolkata'

USE_TZ = True

# FOR STATIC FILES
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]


# Static files (WhiteNoise)

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Cloudinary env vars (used below and for CLOUDINARY_STORAGE further down).
# Media uploads (profile pictures) only move to Cloudinary once these are
# actually configured — otherwise local dev keeps using the local disk it's
# already using, so nothing breaks before the user sets up an account.
CLOUDINARY_CLOUD_NAME = config('CLOUDINARY_CLOUD_NAME', default='')
CLOUDINARY_API_KEY = config('CLOUDINARY_API_KEY', default='')
CLOUDINARY_API_SECRET = config('CLOUDINARY_API_SECRET', default='')

STORAGES = {
    "default": {
        "BACKEND": (
            "cloudinary_storage.storage.MediaCloudinaryStorage" if CLOUDINARY_CLOUD_NAME
            # In production without Cloudinary, fall back to storing
            # uploads as rows in the (already-persistent) database
            # instead of the local disk, which Render's free tier wipes
            # on every redeploy. Local dev keeps using plain disk storage.
            else "employees.storage.DatabaseStorage" if not DEBUG
            else "django.core.files.storage.FileSystemStorage"
        ),
    },

    # WhiteNoise's compressed/manifest backend needs `collectstatic` to have
    # run (it looks up a staticfiles.json manifest) — only switch to it when
    # DEBUG is off, so `manage.py runserver` locally isn't affected.
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

if CLOUDINARY_CLOUD_NAME:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': CLOUDINARY_API_KEY,
        'API_SECRET': CLOUDINARY_API_SECRET,
    }

# django-cloudinary-storage's custom `collectstatic` command still reads the
# old pre-4.2 STATICFILES_STORAGE/DEFAULT_FILE_STORAGE settings directly
# instead of STORAGES, and crashes with AttributeError if they're undefined.
# Django supports defining both as long as they're kept consistent with
# STORAGES, so mirror them here purely for that package's compatibility.
STATICFILES_STORAGE = STORAGES["staticfiles"]["BACKEND"]
DEFAULT_FILE_STORAGE = STORAGES["default"]["BACKEND"]

# FOR AVATAR SELECTION
# Plain filenames relative to static/icons/ - the only consumer is
# employee_detail.html, which builds {% static 'icons/'|add:avatar %} from
# each entry, so these must NOT be full filesystem paths (they used to be,
# via os.path.join(STATICFILES_DIRS[0], ...), which broke under DEBUG=False
# since ManifestStaticFilesStorage validates the resulting path against the
# actual collected static file list).
AVATAR_FILENAMES = ["avatar_01.jpg", "avatar_02.png", "avatar_03.png", "avatar_04.png", "avatar_05.png", "avatar_06.png", "avatar_07.png", "avatar_08.png", "avatar_09.png","avatar_01.jpg","avatar_02.jpg","avatar_03.jpg", "avatar_04.jpg", "avatar_05.jpg", "avatar_06.jpg", "avatar_07.jpg", "avatar_08.jpg","avatar_09.jpg","avatar_10.jpg","avatar_11.jpg","avatar_12.jpg","avatar_13.jpg"]
AVATAR_LIST = AVATAR_FILENAMES


# FOR MEDIA FILES
MEDIA_URL  = '/media/'
BASE_DIR = Path(__file__).resolve().parent.parent

# On Render, attach a persistent disk and point this at its mount path
# (e.g. MEDIA_ROOT=/var/data/media) so uploaded files survive redeploys —
# the default filesystem is wiped on every deploy, unlike a persistent
# disk. Local dev is untouched when this env var isn't set.
MEDIA_ROOT = Path(config('MEDIA_ROOT', default=str(BASE_DIR / 'media')))


AUTH_USER_MODEL = 'accounts.User'


MESSAGE_TAGS = {
    messages.SUCCESS: "success",
    messages.ERROR: "danger",
    messages.WARNING: "warning",
    messages.INFO: "info",
}

# Defaults to the console backend (prints instead of sending) for local dev.
# Set EMAIL_BACKEND/EMAIL_HOST_USER/EMAIL_HOST_PASSWORD in the environment
# (e.g. on Vercel) to send real emails via Gmail SMTP.
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or 'noreply@mantechpublications.com'
DEFAULT_USER_EMAIL = EMAIL_HOST_USER or "mantechadmin@gmail.com"


# HR_EMAIL : hr.mantechpublications@gmail.com
# HR_EMAIL_TOKEN : 7d7f8b4f-8e4f-4a2f-8f4f-4a2f8f4f8f4f
