"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.contrib.messages import constants as messages


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tnpg7zk*c5!9*p0-2jemqyj+o9!jgh-l%zd^s2h%an!knu4vci'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*',
    '192.168.1.7',
    '127.0.0.1',
    'localhost',
]

# When accessing the dev server by IP from other devices, include
# those origins so Django's CSRF check accepts POSTs from them.
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1",
    "http://127.0.0.1:8000",
    "http://192.168.1.7",
    "http://192.168.1.7:8000",
]

# Disable the Cross-Origin-Opener-Policy header in development when using HTTP/local IP.
# This avoids browser warnings for non-HTTPS local network access.
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

# Database connection pooling (stops DB from being a bottleneck)
CONN_MAX_AGE = 60  # reuse DB connections for 60 seconds


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # CUSTOM APPS
    'accounts',
    'employees',
    'attendance',
    'leaves',
    'payroll',
    'dashboard',
    'reports',
    'noticeboard',
    'grievances',
    'mantech_chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',        # ← ADD THIS LINE
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # ← for debugging 
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'grievances.context_processors.admin_notifications',
                'django.template.context_processors.media',  # ← add this for media files
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 20,
            'init_command': (
                'PRAGMA journal_mode=WAL;'      # ← biggest fix — allows multiple readers + 1 writer at same time
                'PRAGMA synchronous=NORMAL;'    # ← faster writes
                'PRAGMA cache_size=-64000;'     # ← 64MB memory cache
                'PRAGMA temp_store=MEMORY;'     # ← temp tables in RAM
                # 'PRAGMA mmap_size=268435456;'   # ← 256MB memory map
            ),
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CUSTOM CONFIGURATION SETTINGS

## settings.py
# SESSION_COOKIE_AGE = 86400          # 1 day in seconds (default is 2 weeks)
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # keep session after browser closes
# SESSION_SAVE_EVERY_REQUEST = True   # refresh session on every request

# settings.py
LOGIN_URL = "/accounts/login/"           # must match your actual login url
LOGIN_REDIRECT_URL = "/accounts/home/"



# FOR DATE
TIME_ZONE = 'Asia/Kolkata'

USE_TZ = True

# FOR STATIC FILES
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]


# Static files (WhiteNoise)

STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },

    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

from django.conf import settings

# FOR AVATAR SELECTION
AVATAR_FILENAMES = ["avatar_01.jpg", "avatar_02.png", "avatar_03.png", "avatar_04.png", "avatar_05.png", "avatar_06.png", "avatar_07.png", "avatar_08.png", "avatar_09.png","avatar_01.jpg","avatar_02.jpg","avatar_03.jpg", "avatar_04.jpg", "avatar_05.jpg", "avatar_06.jpg", "avatar_07.jpg", "avatar_08.jpg","avatar_09.jpg","avatar_10.jpg","avatar_11.jpg","avatar_12.jpg","avatar_13.jpg"]
avatar_source = os.path.join(settings.STATICFILES_DIRS[0], "icons") 
avatar_list = [os.path.join(avatar_source, filename) for filename in AVATAR_FILENAMES]
AVATAR_LIST = avatar_list  # e.g.  /your_project/static/icons/avatar_01.jpg


# FOR MEDIA FILES
MEDIA_URL  = '/media/'
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_ROOT = BASE_DIR / 'media'


AUTH_USER_MODEL = 'accounts.User'


MESSAGE_TAGS = {
    messages.SUCCESS: "success",
    messages.ERROR: "danger",
    messages.WARNING: "warning",
    messages.INFO: "info",
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False  
EMAIL_HOST_USER = "anvdgroup@gmail.com"
EMAIL_HOST_PASSWORD = "mtrx rubw atrq gzfy"
DEFAULT_USER_EMAIL = EMAIL_HOST_USER


# HR_EMAIL : hr.mantechpublications@gmail.com
# HR_EMAIL_TOKEN : 7d7f8b4f-8e4f-4a2f-8f4f-4a2f8f4f8f4f
