# Generated by Django 5.2.14 on 2026-05-22 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notice_type', models.CharField(choices=[('all', 'All Employees'), ('management', 'Management'), ('hr', 'HR Department'), ('accounts', 'Accounts Department'), ('sales', 'Sales Department'), ('editorial', 'Editorial Team'), ('intern', 'Interns')], default='all', max_length=30)),
                ('message_type', models.CharField(choices=[('general', 'General Notice'), ('warning', 'Warning'), ('attendance', 'Attendance'), ('payroll', 'Payroll'), ('holiday', 'Holiday'), ('meeting', 'Meeting'), ('event', 'Event'), ('important', 'Important')], default='general', max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notice Board',
                'verbose_name_plural': 'Notice Board',
                'ordering': ['-created_at'],
            },
        ),
    ]
