# Generated by Django 5.2.14 on 2026-07-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='notice_type',
            field=models.CharField(choices=[('all', 'All Employees'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('it', 'Information Technology'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('admin', 'Administration'), ('accountant', 'Accountant'), ('positive_vibes', 'Positive Vibes Department')], default='all', max_length=30),
        ),
    ]
