# Generated by Django 5.2.14 on 2026-05-28 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('holiday_type', models.CharField(choices=[('Festival', 'Festival'), ('Government Holiday', 'Government Holiday'), ('National Holiday', 'National Holiday'), ('Regional Holiday', 'Regional Holiday'), ('Optional Holiday', 'Optional Holiday'), ('Other', 'Other')], max_length=50)),
                ('custom_type', models.CharField(blank=True, help_text="Used when holiday_type is 'Other'", max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holidays_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
