# Generated by Django 5.2.14 on 2026-06-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payroll_gross_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='earned_basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='earned_da',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='earned_hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
