# Generated by Django 5.2.14 on 2026-06-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payroll_earned_basic_salary_payroll_earned_da_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='da_rate',
            field=models.DecimalField(decimal_places=2, default=60, help_text='DA percentage of basic salary (e.g. 60 for 60%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='payroll',
            name='hra_rate',
            field=models.DecimalField(decimal_places=2, default=40, help_text='HRA percentage of basic salary (e.g. 40 for 40%)', max_digits=5),
        ),
    ]
