# Generated by Django 5.2.14 on 2026-06-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payroll_da_rate_payroll_hra_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='bonus_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='deduction_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='da',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='SA'),
        ),
    ]
