# Generated by Django 5.2.14 on 2026-07-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payroll_bonus_remark_payroll_deduction_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='earned_da',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Earned SA'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='HRA'),
        ),
    ]
