# Generated by Django 5.2.14 on 2026-05-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_status_attendancelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Leave', 'Leave'), ('Sunday', 'Sunday'), ('Half Day', 'Half Day')], default='Present', max_length=20),
        ),
    ]
